name: ucampus_lib
description: uCampus common library
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  get_it: ^4.0.1
  async_redux: ^2.5.8
  rounded_loading_button: ^1.0.4
  flutter_datetime_picker:
    git:
      url: https://github.com/derohimat/flutter_datetime_picker.git
  flutter_picker: ^1.1.3
  cupertino_icons: ^0.1.2
  flutter_map:
    git:
      url: git://github.com/johnpryan/flutter_map.git
      ref: master
  flutter_speed_dial: ^1.2.5
  floating_search_bar: ^0.3.0
  flutter_launcher_icons: ^0.7.4
  device_id: ^0.2.0
  http: ^0.12.1
  utm: ^0.1.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter  
  build_runner: ^1.8.0
  json_serializable: ^3.3.0
  mockito: ^4.1.0

flutter:
  uses-material-design: true
  fonts:
    - family: Krub
      fonts:
        - asset: fonts/Krub-BoldItalic.ttf
        - asset: fonts/Krub-Bold.ttf
        - asset: fonts/Krub-ExtraLightItalic.ttf
        - asset: fonts/Krub-ExtraLight.ttf
        - asset: fonts/Krub-Italic.ttf
        - asset: fonts/Krub-LightItalic.ttf
        - asset: fonts/Krub-Light.ttf
        - asset: fonts/Krub-MediumItalic.ttf
        - asset: fonts/Krub-Medium.ttf
        - asset: fonts/Krub-Regular.ttf
        - asset: fonts/Krub-SemiBoldItalic.ttf
        - asset: fonts/Krub-SemiBold.ttf
